"""
DHCaaS Platform - Enterprise PDF Report Generator v8.0 FINAL
FIXED: Gray monotone charts with EXPLICIT color assignment
Production-ready for Fortune 500 clients
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph,
    Spacer, PageBreak, Image, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import VerticalBarChart
from datetime import datetime
import io
import math
from typing import Dict, List, Any, Optional


class DHCaaSReportCanvas(canvas.Canvas):
    """Custom canvas with enterprise-grade footer on every page"""

    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self.pages = []

    def showPage(self):
        self.pages.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        page_count = len(self.pages)
        for page_num, page in enumerate(self.pages, 1):
            self.__dict__.update(page)
            self.draw_footer(page_num, page_count)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_footer(self, page_num, page_count):
        """Enterprise footer with copyright and confidentiality"""
        self.saveState()

        # Footer line
        self.setStrokeColor(colors.HexColor("#D1D5DB"))
        self.setLineWidth(1)
        self.line(0.75 * inch, 0.65 * inch, letter[0] - 0.75 * inch, 0.65 * inch)

        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#6B7280"))

        # Left: Copyright
        self.drawString(0.75 * inch, 0.5 * inch, "© 2026 DHCaaS Inc. All Rights Reserved.")

        # Right: Generated by + Page numbers
        right_text = f"Generated by DHCaaS Platform | CONFIDENTIAL | Page {page_num} of {page_count}"
        text_width = self.stringWidth(right_text, "Helvetica", 8)
        self.drawString(letter[0] - text_width - 0.75 * inch, 0.5 * inch, right_text)

        self.restoreState()


class DHCaaSPDFGenerator:
    """Enterprise PDF report generator v8.0 - Production Grade"""

    def __init__(self):
        # Enterprise Color Palette
        self.colors = {
            # Brand Colors
            'brand_primary': colors.HexColor('#0F766E'),
            'brand_secondary': colors.HexColor('#1E3A8A'),
            
            # Severity Colors
            'severity_critical': colors.HexColor('#DC2626'),
            'severity_high': colors.HexColor('#F59E0B'),
            'severity_medium': colors.HexColor('#3B82F6'),
            'severity_low': colors.HexColor('#10B981'),
            
            # Quality Dimension Colors - BRIGHT & DISTINCT
            'dimension_completeness': colors.HexColor('#1ABC9C'),  # Bright Teal
            'dimension_accuracy': colors.HexColor('#3498DB'),      # Bright Blue
            'dimension_consistency': colors.HexColor('#2C3E50'),   # Dark Navy
            'dimension_validity': colors.HexColor('#95A5A6'),      # Silver Gray
            
            # Status Indicators
            'status_excellent': colors.HexColor('#10B981'),
            'status_good': colors.HexColor('#3B82F6'),
            'status_fair': colors.HexColor('#F59E0B'),
            'status_poor': colors.HexColor('#DC2626'),
            
            # UI Colors
            'navy': colors.HexColor('#0f172a'),
            'navy_medium': colors.HexColor('#1e293b'),
            'navy_light': colors.HexColor('#334155'),
            'teal': colors.HexColor('#14b8a6'),
            'teal_dark': colors.HexColor('#0d9488'),
            'slate': colors.HexColor('#475569'),
            'slate_light': colors.HexColor('#64748b'),
            'text_primary': colors.HexColor('#111827'),
            'text_secondary': colors.HexColor('#6B7280'),
            'border': colors.HexColor('#D1D5DB'),
            'gray_light': colors.HexColor('#e2e8f0'),
            'light_gray': colors.HexColor('#f1f5f9'),
            'zebra_gray': colors.HexColor('#f8fafc'),
            'white': colors.white,
            'insight_bg': colors.HexColor('#fffbeb'),
            'insight_border': colors.HexColor('#fbbf24'),
        }

        # Initialize styles
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        """Define custom paragraph styles with consistent typography"""

        # Page Title (24pt, Bold, Navy)
        self.styles.add(ParagraphStyle(
            name='PageTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=self.colors['brand_secondary'],
            spaceAfter=6,
            spaceBefore=0,
            fontName='Helvetica-Bold',
            leading=28
        ))

        # Section Header (16pt, Bold, Teal)
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=self.colors['brand_primary'],
            spaceAfter=8,
            spaceBefore=16,
            fontName='Helvetica-Bold',
            leading=20
        ))

        # Subsection header
        self.styles.add(ParagraphStyle(
            name='SubsectionHeader',
            parent=self.styles['Heading3'],
            fontSize=14,
            textColor=self.colors['teal_dark'],
            spaceAfter=8,
            spaceBefore=16,
            fontName='Helvetica-Bold',
            leading=18
        ))

        # Body text (11pt, Regular, Dark Gray)
        self.styles.add(ParagraphStyle(
            name='DHCBodyText',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=self.colors['text_primary'],
            leading=16,
            spaceAfter=10,
            alignment=TA_JUSTIFY
        ))

        # AI Insight text
        self.styles.add(ParagraphStyle(
            name='AIInsight',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=self.colors['navy_light'],
            leading=14,
            leftIndent=28,
            rightIndent=12,
            spaceAfter=8
        ))

        # Executive Summary
        self.styles.add(ParagraphStyle(
            name='ExecutiveSummary',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=self.colors['navy_medium'],
            leading=17,
            spaceAfter=12,
            alignment=TA_JUSTIFY,
            leftIndent=20,
            rightIndent=20
        ))

        # Key Finding
        self.styles.add(ParagraphStyle(
            name='KeyFinding',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=self.colors['navy_light'],
            leading=14,
            leftIndent=25,
            bulletIndent=10,
            spaceAfter=6
        ))

    def create_section_header_with_underline(self, text: str) -> List:
        """Create section header with teal underline"""
        elements = []
        elements.append(Paragraph(text, self.styles['PageTitle']))

        underline_data = [['']]
        underline_table = Table(underline_data, colWidths=[6.5 * inch])
        underline_table.setStyle(TableStyle([
            ('LINEBELOW', (0, 0), (-1, -1), 3, self.colors['brand_primary']),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(underline_table)
        elements.append(Spacer(1, 0.15 * inch))

        return elements

    def create_ai_insight_box(self, insight_text: str) -> List:
        """Create AI insight box with light yellow background"""
        elements = []

        insight_content = f"💡 <b>AI Insight:</b> {insight_text}"
        insight_data = [[Paragraph(insight_content, self.styles['AIInsight'])]]

        insight_table = Table(insight_data, colWidths=[6.5 * inch])
        insight_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), self.colors['insight_bg']),
            ('BOX', (0, 0), (-1, -1), 1.5, self.colors['insight_border']),
            ('ROUNDEDCORNERS', [6, 6, 6, 6]),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ]))

        elements.append(insight_table)
        elements.append(Spacer(1, 0.2 * inch))

        return elements

    def create_pie_chart(self, data_dict: Dict[str, float], title: str, 
                        chart_type: str = 'severity',
                        width: float = 4 * inch, height: float = 3 * inch) -> Drawing:
        """
        Create professional pie chart with EXPLICIT color assignment
        FIXED: No more gray monotone - colors are assigned directly by index
        
        Args:
            data_dict: Data to chart {label: value}
            title: Chart title
            chart_type: 'severity' or 'dimension' (determines color scheme)
            width: Chart width
            height: Chart height
        """
        drawing = Drawing(width, height)

        pie = Pie()
        pie.x = width / 2 - 100
        pie.y = height / 2 - 50
        pie.width = 180
        pie.height = 180

        pie.data = list(data_dict.values())
        
        # Create labels with percentages
        total = sum(data_dict.values())
        if total > 0:
            pie.labels = [f"{k}\n{(v/total*100):.1f}%" for k, v in data_dict.items()]
        else:
            pie.labels = list(data_dict.keys())

        # Slice styling
        pie.slices.strokeWidth = 2
        pie.slices.strokeColor = colors.white
        pie.slices.fontName = 'Helvetica-Bold'
        pie.slices.fontSize = 9
        pie.slices.fontColor = colors.HexColor('#1E293B')

        # ═══════════════════════════════════════════════════════════════
        # CRITICAL FIX: Direct color assignment by slice index
        # NO lookup, NO fallback to gray - explicit colors for each slice
        # ═══════════════════════════════════════════════════════════════
        
        if chart_type == 'dimension':
            # Quality Dimensions - BRIGHT DISTINCT COLORS (IN ORDER)
            color_sequence = [
                colors.HexColor('#1ABC9C'),  # Teal (Completeness)
                colors.HexColor('#3498DB'),  # Blue (Accuracy)
                colors.HexColor('#2C3E50'),  # Navy (Consistency)
                colors.HexColor('#95A5A6'),  # Gray (Validity)
            ]
        elif chart_type == 'severity':
            # Severity - RED/AMBER/BLUE/GREEN (IN ORDER)
            color_sequence = [
                colors.HexColor('#DC2626'),  # Red (Critical)
                colors.HexColor('#F59E0B'),  # Amber (High)
                colors.HexColor('#3B82F6'),  # Blue (Medium)
                colors.HexColor('#10B981'),  # Green (Low)
            ]
        else:
            # Default fallback
            color_sequence = [
                colors.HexColor('#3B82F6'),  # Blue
                colors.HexColor('#10B981'),  # Green
                colors.HexColor('#F59E0B'),  # Amber
                colors.HexColor('#DC2626'),  # Red
            ]

        # APPLY COLORS DIRECTLY TO EACH SLICE BY INDEX
        for i in range(len(pie.data)):
            # Use modulo to cycle through colors if more data than colors
            color_index = i % len(color_sequence)
            pie.slices[i].fillColor = color_sequence[color_index]
            
            # Enhanced label positioning
            pie.slices[i].labelRadius = 1.2
            pie.slices[i].fontColor = colors.HexColor('#1E293B')

        # Add title
        title_string = String(width / 2, height - 20, title, textAnchor='middle')
        title_string.fontName = 'Helvetica-Bold'
        title_string.fontSize = 14
        title_string.fillColor = self.colors['brand_secondary']

        drawing.add(pie)
        drawing.add(title_string)

        return drawing

    def create_cover_page(self, c, width, height, report_data: Dict[str, Any]):
        """
        Enterprise Cover Page - MINIMAL DESIGN (No data tables/metrics)
        Cover page = Identity only
        """
        c.saveState()

        # Deep Navy Background
        c.setFillColor(self.colors['navy'])
        c.rect(0, 0, width, height, fill=1, stroke=0)

        # TOP: DHCaaS Branding
        header_y = height - 1.5 * inch

        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 48)
        c.drawCentredString(width / 2, header_y, "DHCaaS")

        c.setFillColor(self.colors['teal'])
        c.setFont("Helvetica", 10)
        letter_spacing_text = "  ".join("INTELLIGENCE ENGINE")
        c.drawCentredString(width / 2, header_y - 32, letter_spacing_text)

        # Decorative line
        c.setStrokeColor(self.colors['teal'])
        c.setLineWidth(3)
        c.line(width / 2 - 2 * inch, header_y - 50,
               width / 2 + 2 * inch, header_y - 50)

        # CENTER: Report Title
        title_y = height / 2 + 1 * inch

        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 36)
        c.drawCentredString(width / 2, title_y, "Data Quality Assessment Report")

        # Decorative underline
        c.setStrokeColor(self.colors['teal'])
        c.setLineWidth(2)
        c.line(width / 2 - 3.5 * inch, title_y - 15,
               width / 2 + 3.5 * inch, title_y - 15)

        # MIDDLE: Metadata
        meta_y = height / 2 - 0.5 * inch

        datasource_name = report_data.get('datasource_name', 'Enterprise Data Source')
        scan_date = report_data.get('scan_date', datetime.now().strftime('%B %d, %Y'))
        organization = report_data.get('organization', 'DHCaaS Platform')

        c.setFillColor(self.colors['gray_light'])
        c.setFont("Helvetica", 14)
        c.drawCentredString(width / 2, meta_y, f"Data Source: {datasource_name}")
        
        c.setFont("Helvetica", 12)
        c.drawCentredString(width / 2, meta_y - 30, f"Generated: {scan_date}")
        c.drawCentredString(width / 2, meta_y - 55, f"Organization: {organization}")

        # BOTTOM: Report ID & Confidentiality
        footer_y = 2 * inch

        report_id = report_data.get('report_id', f"DQR-{datetime.now().strftime('%Y%m%d-%H%M%S')}")
        c.setFont("Helvetica", 10)
        c.setFillColor(self.colors['slate_light'])
        c.drawString(0.75 * inch, footer_y, f"Report ID: {report_id}")

        c.drawRightString(width - 0.75 * inch, footer_y, "Version 8.0")

        c.setFont("Helvetica-Bold", 9)
        c.setFillColor(self.colors['teal'])
        banner_text = "  ".join("CONFIDENTIAL   •   ENTERPRISE GRADE   •   AI-POWERED")
        c.drawCentredString(width / 2, footer_y - 35, banner_text)

        c.setFont("Helvetica-Oblique", 8)
        c.setFillColor(self.colors['slate_light'])
        c.drawCentredString(width / 2, footer_y - 55,
                           "This report contains proprietary and confidential information")

        c.restoreState()

    def create_executive_summary_page(self, report_data: Dict[str, Any]) -> List:
        """Create executive summary with metrics table"""
        elements = []

        elements.extend(self.create_section_header_with_underline("Executive Summary"))

        summary_text = report_data.get('executive_summary',
            "This comprehensive data quality assessment provides an in-depth analysis of your data assets. "
            "Our AI-powered platform examines multiple quality dimensions including completeness, accuracy, "
            "consistency, and validity to provide actionable insights."
        )
        elements.append(Paragraph(summary_text, self.styles['ExecutiveSummary']))
        elements.append(Spacer(1, 0.25 * inch))

        # Key Metrics Table (moved from cover page)
        elements.append(Paragraph("Key Metrics", self.styles['SectionHeader']))
        elements.append(Spacer(1, 0.1 * inch))

        metrics = report_data.get('key_metrics', {})

        metrics_data = [
            ["Metric", "Value"],
            ["Overall Data Quality Score", f"{metrics.get('overall_score', 0)}%"],
            ["Total Records Analyzed", f"{metrics.get('total_records', 0):,}"],
            ["Issues Identified", str(metrics.get('issues_count', 0))],
            ["Critical Issues", str(metrics.get('critical_issues', 0))]
        ]

        metrics_table = Table(metrics_data, colWidths=[3.5 * inch, 3 * inch])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.colors['navy_medium']),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('FONTSIZE', (0, 1), (-1, -1), 11),
            ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('RIGHTPADDING', (0, 0), (-1, -1), 12),
            ('LINEBELOW', (0, 0), (-1, 0), 2, self.colors['brand_primary']),
            ('GRID', (0, 1), (-1, -1), 0.5, self.colors['border']),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, self.colors['zebra_gray']])
        ]))

        elements.append(metrics_table)
        elements.append(Spacer(1, 0.2 * inch))

        # AI Insight
        overall_score = metrics.get('overall_score', 0)
        critical_count = metrics.get('critical_issues', 0)
        total_issues = metrics.get('issues_count', 0)

        if overall_score >= 95:
            insight = "Outstanding data quality! Your data meets the highest enterprise standards. Continue monitoring to maintain excellence."
        elif overall_score >= 90:
            insight = "Excellent data quality detected. Minor optimizations available to achieve perfect scores."
        elif overall_score >= 80:
            insight = f"Good data quality overall. Address {critical_count} critical issues to reach excellence level."
        elif overall_score >= 70:
            insight = f"Fair data quality. {total_issues} issues identified requiring attention, with {critical_count} critical items demanding immediate action."
        else:
            insight = f"Data quality below acceptable threshold. Urgent intervention required: {critical_count} critical issues pose significant business risk."

        elements.extend(self.create_ai_insight_box(insight))

        # Key Findings
        elements.append(Paragraph("Key Findings", self.styles['SectionHeader']))
        elements.append(Spacer(1, 0.1 * inch))

        findings = report_data.get('key_findings', [
            "Data completeness exceeds 92% across all fields",
            "Accuracy metrics indicate strong data validation processes",
            "Consistency rules show minor violations in 3 data fields",
            "Immediate action recommended for critical validation failures"
        ])

        for finding in findings:
            elements.append(Paragraph(f"• {finding}", self.styles['KeyFinding']))

        elements.append(PageBreak())
        return elements

    def create_data_profile_section(self, report_data: Dict[str, Any]) -> List:
        """Create detailed data profile section"""
        elements = []

        elements.extend(self.create_section_header_with_underline("Data Profile Overview"))

        profile = report_data.get('data_profile', {})

        source_info = [
            ["Attribute", "Value"],
            ["Data Source Name", profile.get('datasource_name', 'N/A')],
            ["Connection Type", profile.get('connection_type', 'N/A')],
            ["Total Tables/Collections", str(profile.get('total_tables', 0))],
            ["Total Columns/Fields", str(profile.get('total_columns', 0))],
            ["Total Records", f"{profile.get('total_records', 0):,}"],
            ["Data Volume", profile.get('data_volume', 'N/A')],
            ["Last Updated", profile.get('last_updated', 'N/A')]
        ]

        source_table = Table(source_info, colWidths=[2.5 * inch, 4 * inch])
        source_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.colors['navy_medium']),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('RIGHTPADDING', (0, 0), (-1, -1), 12),
            ('LINEBELOW', (0, 0), (-1, 0), 2, self.colors['brand_primary']),
            ('GRID', (0, 1), (-1, -1), 0.5, self.colors['border']),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, self.colors['zebra_gray']])
        ]))

        elements.append(source_table)
        elements.append(Spacer(1, 0.2 * inch))

        # AI Insight
        total_records = profile.get('total_records', 0)
        if total_records > 1000000:
            profile_insight = f"Large-scale dataset detected ({total_records:,} records). Enterprise-grade monitoring infrastructure recommended for continuous quality assurance."
        elif total_records > 100000:
            profile_insight = f"Medium-scale dataset ({total_records:,} records). Automated quality checks should run daily to maintain data integrity."
        elif total_records > 10000:
            profile_insight = f"Standard dataset size ({total_records:,} records). Regular quality audits recommended on weekly basis."
        else:
            profile_insight = f"Small dataset ({total_records:,} records) suitable for manual validation. Consider implementing automated checks as data volume grows."

        elements.extend(self.create_ai_insight_box(profile_insight))

        # Data Quality Dimensions
        elements.append(Paragraph("Data Quality Dimensions", self.styles['SectionHeader']))
        elements.append(Spacer(1, 0.1 * inch))

        dimensions = report_data.get('quality_dimensions', {})

        if dimensions:
            dim_data = [["Dimension", "Score", "Status", "Description"]]

            for dim_name, dim_info in dimensions.items():
                score = dim_info.get('score', 0)
                status = self._get_status_indicator(score)
                description = dim_info.get('description', '')

                dim_data.append([
                    dim_name.replace('_', ' ').title(),
                    f"{score}%",
                    status,
                    description
                ])

            dim_table = Table(dim_data, colWidths=[1.5 * inch, 0.8 * inch, 1.1 * inch, 3.1 * inch])
            dim_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.colors['navy_medium']),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('FONTSIZE', (0, 1), (-1, -1), 10),
                ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
                ('ALIGN', (0, 1), (2, -1), 'CENTER'),
                ('ALIGN', (3, 1), (3, -1), 'LEFT'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('TOPPADDING', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
                ('LEFTPADDING', (0, 0), (-1, -1), 10),
                ('RIGHTPADDING', (0, 0), (-1, -1), 10),
                ('LINEBELOW', (0, 0), (-1, 0), 2, self.colors['brand_primary']),
                ('GRID', (0, 1), (-1, -1), 0.5, self.colors['border']),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, self.colors['zebra_gray']])
            ]))

            elements.append(dim_table)
            elements.append(Spacer(1, 0.25 * inch))

            # FIXED: Pie chart with explicit dimension colors
            dim_chart_data = {k.replace('_', ' ').title(): v.get('score', 0) 
                            for k, v in dimensions.items()}
            chart = self.create_pie_chart(
                dim_chart_data, 
                "Quality Dimensions Breakdown",
                chart_type='dimension',  # Uses dimension color sequence
                width=5 * inch, 
                height=3.5 * inch
            )
            elements.append(chart)

        elements.append(PageBreak())
        return elements

    def _get_status_indicator(self, score: float) -> str:
        """Return status text with emoji based on score"""
        if score >= 95:
            return "✓ Excellent"
        elif score >= 90:
            return "✓ Good"
        elif score >= 75:
            return "⚠ Fair"
        elif score >= 60:
            return "⚠ Needs Attention"
        else:
            return "✗ Poor"

    def create_issues_section(self, report_data: Dict[str, Any]) -> List:
        """Create issues section with severity-based charts"""
        elements = []

        elements.extend(self.create_section_header_with_underline("Data Quality Issues"))

        issues = report_data.get('issues', [])

        if not issues:
            elements.append(Paragraph(
                "✓ <b>No data quality issues detected.</b> Your data meets all quality standards and validation rules.",
                self.styles['DHCBodyText']
            ))
            elements.extend(self.create_ai_insight_box(
                "Excellent! Zero issues detected across all quality dimensions. Your data governance practices are working effectively. "
                "Continue regular monitoring to maintain this high standard."
            ))
            elements.append(PageBreak())
            return elements

        # Count by severity
        critical_issues = [i for i in issues if i.get('severity', '').lower() == 'critical']
        high_issues = [i for i in issues if i.get('severity', '').lower() == 'high']
        medium_issues = [i for i in issues if i.get('severity', '').lower() == 'medium']
        low_issues = [i for i in issues if i.get('severity', '').lower() == 'low']

        summary = (f"Total of <b>{len(issues)}</b> issues identified: "
                  f"<font color='#DC2626'><b>{len(critical_issues)} Critical</b></font>, "
                  f"<font color='#F59E0B'>{len(high_issues)} High</font>, "
                  f"<font color='#3B82F6'>{len(medium_issues)} Medium</font>, "
                  f"<font color='#10B981'>{len(low_issues)} Low</font> priority.")
        elements.append(Paragraph(summary, self.styles['DHCBodyText']))
        elements.append(Spacer(1, 0.2 * inch))

        # Severity pie chart
        severity_data = {}
        if len(critical_issues) > 0:
            severity_data['Critical'] = len(critical_issues)
        if len(high_issues) > 0:
            severity_data['High'] = len(high_issues)
        if len(medium_issues) > 0:
            severity_data['Medium'] = len(medium_issues)
        if len(low_issues) > 0:
            severity_data['Low'] = len(low_issues)

        if severity_data:
            chart = self.create_pie_chart(
                severity_data, 
                "Issues by Severity",
                chart_type='severity',  # Uses severity color sequence
                width=5 * inch, 
                height=3.5 * inch
            )
            elements.append(chart)
            elements.append(Spacer(1, 0.25 * inch))

        # Critical & High Priority Issues Table
        if critical_issues or high_issues:
            elements.append(Paragraph("Critical & High Priority Issues", self.styles['SectionHeader']))
            elements.append(Spacer(1, 0.1 * inch))

            priority_issues = critical_issues + high_issues
            elements.extend(self._create_issues_table(priority_issues[:10]))
            elements.append(Spacer(1, 0.2 * inch))

            # AI Insight
            crit_percent = round((len(critical_issues) / len(issues)) * 100) if len(issues) > 0 else 0
            total_high_crit = len(critical_issues) + len(high_issues)
            
            if crit_percent >= 40:
                issue_insight = (f"<b>HIGH RISK:</b> {crit_percent}% of issues are Critical severity, indicating significant data integrity concerns. "
                               f"Immediate remediation required within 24-48 hours to prevent business impact.")
            elif crit_percent >= 25:
                issue_insight = (f"<b>MODERATE RISK:</b> {crit_percent}% Critical issues detected. "
                               f"Prioritize {len(critical_issues)} critical items for resolution within 7 days.")
            elif total_high_crit > 0:
                issue_insight = (f"{total_high_crit} high-priority issues require attention. "
                               f"Address critical items first, then work through high-severity cases systematically.")
            else:
                issue_insight = "Most issues are low/medium severity. Schedule remediation as part of regular data quality maintenance cycle."

            elements.extend(self.create_ai_insight_box(issue_insight))

        # Medium & Low Priority Issues Summary
        if medium_issues or low_issues:
            elements.append(Paragraph("Medium & Low Priority Issues", self.styles['SectionHeader']))
            elements.append(Spacer(1, 0.1 * inch))

            summary_text = (f"<b>{len(medium_issues + low_issues)}</b> additional issues detected at medium/low severity. "
                          "These should be addressed as part of routine data quality maintenance. "
                          "Full details available in system logs.")
            elements.append(Paragraph(summary_text, self.styles['DHCBodyText']))

        elements.append(PageBreak())
        return elements

    def _create_issues_table(self, issues: List[Dict]) -> List:
        """Create professionally formatted issues table"""
        elements = []

        issue_data = [["#", "Severity", "Rule", "Column/Field", "Affected Rows"]]

        for idx, issue in enumerate(issues, 1):
            issue_data.append([
                str(idx),
                issue.get('severity', 'N/A'),
                issue.get('rule_name', issue.get('title', 'N/A')),
                issue.get('column_name', issue.get('datasource', 'N/A')),
                str(issue.get('affected_rows', 'Unknown'))
            ])

        issue_table = Table(issue_data,
                           colWidths=[0.4 * inch, 1 * inch, 2.2 * inch, 1.7 * inch, 1.2 * inch])

        issue_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.colors['navy_medium']),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('ALIGN', (0, 0), (0, -1), 'CENTER'),
            ('ALIGN', (1, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (4, 0), (4, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('LINEBELOW', (0, 0), (-1, 0), 2, self.colors['brand_primary']),
            ('GRID', (0, 1), (-1, -1), 0.5, self.colors['border']),
        ]))

        # Apply severity-based row colors
        for i, issue in enumerate(issues, 1):
            severity = issue.get('severity', '').lower()
            if severity == 'critical':
                bg_color = colors.HexColor('#FEE2E2')
            elif severity == 'high':
                bg_color = colors.HexColor('#FEF3C7')
            else:
                bg_color = colors.white

            issue_table.setStyle(TableStyle([
                ('BACKGROUND', (0, i), (-1, i), bg_color)
            ]))

        elements.append(issue_table)
        return elements

    def create_recommendations_section(self, report_data: Dict[str, Any]) -> List:
        """Create recommendations with proper column widths"""
        elements = []

        elements.extend(self.create_section_header_with_underline("Recommendations & Action Plan"))

        recommendations = report_data.get('recommendations', [
            {
                'priority': 'High',
                'category': 'Critical Issues',
                'action': 'Resolve 2 critical incidents immediately',
                'impact': 'Prevent data compliance violations',
            },
            {
                'priority': 'High',
                'category': 'Data Quality',
                'action': 'Address 1 high-priority incidents',
                'impact': 'Improve overall data quality score',
            },
            {
                'priority': 'Medium',
                'category': 'Data Governance',
                'action': 'Implement continuous data quality monitoring',
                'impact': 'Proactive detection of data quality issues',
            },
            {
                'priority': 'Low',
                'category': 'Data Documentation',
                'action': 'Document data quality standards and policies',
                'impact': 'Establish team ownership and clear guidelines',
            }
        ])

        rec_data = [["Priority", "Category", "Recommended Action", "Expected Impact"]]

        for rec in recommendations:
            rec_data.append([
                rec.get('priority', 'N/A'),
                rec.get('category', 'N/A'),
                rec.get('action', 'N/A'),
                rec.get('impact', 'N/A')
            ])

        # Column widths total 6.5 inches exactly
        rec_table = Table(rec_data,
                         colWidths=[0.75 * inch, 1.25 * inch, 2.5 * inch, 2.0 * inch])

        rec_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.colors['navy_medium']),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('LINEBELOW', (0, 0), (-1, 0), 2, self.colors['brand_primary']),
            ('GRID', (0, 1), (-1, -1), 0.5, self.colors['border']),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, self.colors['zebra_gray']]),
            ('WORDWRAP', (0, 0), (-1, -1), True),
        ]))

        # Priority-based color coding
        for i, rec in enumerate(recommendations, 1):
            priority = rec.get('priority', '').lower()
            if priority == 'high':
                rec_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, i), (0, i), colors.HexColor('#FEE2E2')),
                    ('TEXTCOLOR', (0, i), (0, i), colors.HexColor('#991B1B')),
                    ('FONTNAME', (0, i), (0, i), 'Helvetica-Bold'),
                ]))
            elif priority == 'medium':
                rec_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, i), (0, i), colors.HexColor('#FEF3C7')),
                    ('TEXTCOLOR', (0, i), (0, i), colors.HexColor('#92400E')),
                    ('FONTNAME', (0, i), (0, i), 'Helvetica-Bold'),
                ]))
            elif priority == 'low':
                rec_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, i), (0, i), colors.HexColor('#DBEAFE')),
                    ('TEXTCOLOR', (0, i), (0, i), colors.HexColor('#1E40AF')),
                ]))

        elements.append(rec_table)
        elements.append(Spacer(1, 0.2 * inch))

        # AI Insight
        high_priority = sum(1 for r in recommendations if r.get('priority', '').lower() == 'high')
        
        if high_priority >= 2:
            rec_insight = (f"<b>URGENT:</b> {high_priority} high-priority actions require immediate attention. "
                         f"Execute these within 7 days to prevent data quality degradation.")
        elif high_priority == 1:
            rec_insight = "1 high-priority action identified. Address this first, then schedule medium-priority tasks."
        else:
            rec_insight = "All recommendations are medium/low priority. Schedule as part of regular maintenance."

        elements.extend(self.create_ai_insight_box(rec_insight))

        return elements

    def generate_report(self, report_data: Dict[str, Any], output_path: str) -> str:
        """Generate complete enterprise PDF report"""
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=1 * inch,
            bottomMargin=1 * inch,
            title=f"DHCaaS Data Quality Report - {report_data.get('datasource_name', 'Report')}",
            author="DHCaaS Platform",
            subject="Data Quality Assessment Report"
        )

        story = []
        story.extend(self.create_executive_summary_page(report_data))
        story.extend(self.create_data_profile_section(report_data))
        story.extend(self.create_issues_section(report_data))
        story.extend(self.create_recommendations_section(report_data))

        def on_first_page(canvas_obj, doc):
            self.create_cover_page(canvas_obj, letter[0], letter[1], report_data)

        def on_later_pages(canvas_obj, doc):
            canvas_obj.saveState()
            canvas_obj.setFont('Helvetica', 9)
            canvas_obj.setFillColor(self.colors['text_secondary'])
            
            datasource = report_data.get('datasource_name', 'N/A')
            if len(datasource) > 50:
                datasource = datasource[:47] + "..."
            canvas_obj.drawString(0.75 * inch, letter[1] - 0.5 * inch,
                                f"DHCaaS Report - {datasource}")
            
            canvas_obj.drawRightString(letter[0] - 0.75 * inch, letter[1] - 0.5 * inch,
                                     datetime.now().strftime('%B %d, %Y'))
            canvas_obj.restoreState()

        doc.build(
            story,
            onFirstPage=on_first_page,
            onLaterPages=on_later_pages,
            canvasmaker=DHCaaSReportCanvas
        )

        return output_path

    def generate_report_buffer(self, report_data: Dict[str, Any]) -> io.BytesIO:
        """Generate PDF in memory buffer"""
        buffer = io.BytesIO()

        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=1 * inch,
            bottomMargin=1 * inch
        )

        story = []
        story.extend(self.create_executive_summary_page(report_data))
        story.extend(self.create_data_profile_section(report_data))
        story.extend(self.create_issues_section(report_data))
        story.extend(self.create_recommendations_section(report_data))

        def on_first_page(canvas_obj, doc):
            self.create_cover_page(canvas_obj, letter[0], letter[1], report_data)

        def on_later_pages(canvas_obj, doc):
            canvas_obj.saveState()
            canvas_obj.setFont('Helvetica', 9)
            canvas_obj.setFillColor(self.colors['text_secondary'])
            canvas_obj.drawString(0.75 * inch, letter[1] - 0.5 * inch,
                                f"DHCaaS Report - {report_data.get('datasource_name', 'N/A')}")
            canvas_obj.restoreState()

        doc.build(story, onFirstPage=on_first_page, onLaterPages=on_later_pages,
                 canvasmaker=DHCaaSReportCanvas)

        buffer.seek(0)
        return buffer
