// src/pages/GlossaryPage.tsx
import React, { useState } from 'react';
import { Search, BookOpen, Plus, Tag, User, CheckCircle2, Clock, Filter } from 'lucide-react';



// ===== TYPES =====
interface GlossaryTerm {
  id: string;
  term: string;
  definition: string;
  domain: string;
  owner: string;
  status: 'Draft' | 'Approved' | 'Under Review';
  lastUpdated: string;
}



// ===== MOCK DATA =====
const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    id: '1',
    term: 'Active Customer',
    definition: 'A customer who has made at least one purchase or engaged with the platform within the last 90 days. Used to measure customer engagement and retention metrics.',
    domain: 'Sales',
    owner: 'Sarah Johnson',
    status: 'Approved',
    lastUpdated: '2026-01-15',
  },
  {
    id: '2',
    term: 'Churn Rate',
    definition: 'The percentage of customers who discontinue their subscription or stop using the service during a given time period. Calculated as (Customers Lost / Total Customers at Start) × 100.',
    domain: 'Finance',
    owner: 'Michael Chen',
    status: 'Approved',
    lastUpdated: '2026-01-20',
  },
  {
    id: '3',
    term: 'PII (Personally Identifiable Information)',
    definition: 'Any data that can be used to identify a specific individual, including name, email address, phone number, social security number, or IP address. Must be handled according to GDPR and CCPA requirements.',
    domain: 'Compliance',
    owner: 'Emily Rodriguez',
    status: 'Approved',
    lastUpdated: '2026-02-01',
  },
  {
    id: '4',
    term: 'Data Quality Score',
    definition: 'A composite metric (0-100) that measures the overall health of a dataset based on completeness, accuracy, consistency, timeliness, and validity dimensions.',
    domain: 'Data Governance',
    owner: 'David Park',
    status: 'Under Review',
    lastUpdated: '2026-02-05',
  },
  {
    id: '5',
    term: 'Customer Lifetime Value (CLV)',
    definition: 'The predicted net profit attributed to the entire future relationship with a customer. Calculated using historical purchase patterns, retention rates, and average order values.',
    domain: 'Sales',
    owner: 'Sarah Johnson',
    status: 'Draft',
    lastUpdated: '2026-02-06',
  },
  {
    id: '6',
    term: 'Monthly Recurring Revenue (MRR)',
    definition: 'The predictable total revenue generated by active subscriptions in a month. Includes new MRR, expansion MRR, and excludes churned MRR.',
    domain: 'Finance',
    owner: 'Michael Chen',
    status: 'Approved',
    lastUpdated: '2026-01-28',
  },
  {
    id: '7',
    term: 'Data Steward',
    definition: 'An individual responsible for maintaining data quality, enforcing data policies, and ensuring compliance with governance standards for a specific domain or dataset.',
    domain: 'Data Governance',
    owner: 'David Park',
    status: 'Approved',
    lastUpdated: '2026-01-10',
  },
  {
    id: '8',
    term: 'Sensitive Data',
    definition: 'Information that must be protected from unauthorized access to safeguard privacy or security, including financial data, health records, and authentication credentials.',
    domain: 'Compliance',
    owner: 'Emily Rodriguez',
    status: 'Under Review',
    lastUpdated: '2026-02-07',
  },
];



// ===== MAIN COMPONENT =====
const GlossaryPage: React.FC = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedDomain, setSelectedDomain] = useState<string>('All');
  const [selectedStatus, setSelectedStatus] = useState<string>('All');



  // Get unique domains and statuses
  const domains = ['All', ...Array.from(new Set(GLOSSARY_TERMS.map(t => t.domain)))];
  const statuses = ['All', 'Approved', 'Under Review', 'Draft'];



  // Filter terms
  const filteredTerms = GLOSSARY_TERMS.filter(term => {
    const matchesSearch = 
      term.term.toLowerCase().includes(searchQuery.toLowerCase()) ||
      term.definition.toLowerCase().includes(searchQuery.toLowerCase()) ||
      term.domain.toLowerCase().includes(searchQuery.toLowerCase()) ||
      term.owner.toLowerCase().includes(searchQuery.toLowerCase());
    
    const matchesDomain = selectedDomain === 'All' || term.domain === selectedDomain;
    const matchesStatus = selectedStatus === 'All' || term.status === selectedStatus;
    
    return matchesSearch && matchesDomain && matchesStatus;
  });



  // Status badge styling
  const getStatusStyle = (status: string) => {
    switch (status) {
      case 'Approved':
        return 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400';
      case 'Under Review':
        return 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400';
      case 'Draft':
        return 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-400';
      default:
        return 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-400';
    }
  };



  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'Approved':
        return <CheckCircle2 className="w-4 h-4" />;
      case 'Under Review':
        return <Clock className="w-4 h-4" />;
      case 'Draft':
        return <Clock className="w-4 h-4" />;
      default:
        return <Clock className="w-4 h-4" />;
    }
  };



  return (
    <div className="min-h-screen bg-slate-50 dark:bg-gray-900 transition-colors duration-300">
      {/* Header Section */}
      <div className="bg-white dark:bg-gray-800 border-b border-slate-200 dark:border-gray-700 transition-colors duration-300">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {/* Title & Description */}
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 bg-gradient-to-br from-purple-600 to-blue-600 rounded-xl flex items-center justify-center">
              <BookOpen className="w-6 h-6 text-white" />
            </div>
            <h1 className="text-3xl font-bold text-slate-900 dark:text-white">
              Business Glossary
            </h1>
          </div>
          <p className="text-slate-600 dark:text-gray-400 mb-6">
            Define and manage standard business terminology across your organization
          </p>



          {/* Search & Actions Bar */}
          <div className="flex flex-col sm:flex-row gap-4">
            {/* Search Input */}
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400 dark:text-gray-500" />
              <input
                type="text"
                placeholder="Search terms, definitions, owners..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                aria-label="Search glossary terms"
                className="w-full pl-10 pr-4 py-2.5 bg-white dark:bg-gray-900 border border-slate-300 dark:border-gray-700 rounded-lg text-slate-900 dark:text-white placeholder-slate-400 dark:placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-colors duration-300"
              />
            </div>



            {/* Add New Term Button */}
            <button 
              aria-label="Add new glossary term"
              className="inline-flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-lg hover:shadow-lg hover:shadow-purple-600/30 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-offset-2 transition-all duration-200 font-medium"
            >
              <Plus className="w-5 h-5" />
              Add New Term
            </button>
          </div>



          {/* Filters */}
          <div className="flex flex-wrap items-center gap-3 mt-4">
            <div className="flex items-center gap-2">
              <Filter className="w-4 h-4 text-slate-500 dark:text-gray-400" />
              <span className="text-sm font-medium text-slate-700 dark:text-gray-300">Filters:</span>
            </div>



            {/* Domain Filter */}
            <select
              value={selectedDomain}
              onChange={(e) => setSelectedDomain(e.target.value)}
              aria-label="Filter by domain"
              className="px-3 py-1.5 bg-white dark:bg-gray-800 border border-slate-300 dark:border-gray-700 rounded-lg text-sm text-slate-700 dark:text-gray-300 focus:outline-none focus:ring-2 focus:ring-purple-500 transition-colors duration-300"
            >
              {domains.map(domain => (
                <option key={domain} value={domain}>{domain}</option>
              ))}
            </select>



            {/* Status Filter */}
            <select
              value={selectedStatus}
              onChange={(e) => setSelectedStatus(e.target.value)}
              aria-label="Filter by status"
              className="px-3 py-1.5 bg-white dark:bg-gray-800 border border-slate-300 dark:border-gray-700 rounded-lg text-sm text-slate-700 dark:text-gray-300 focus:outline-none focus:ring-2 focus:ring-purple-500 transition-colors duration-300"
            >
              {statuses.map(status => (
                <option key={status} value={status}>{status}</option>
              ))}
            </select>



            {/* Results Count */}
            <span className="text-sm text-slate-500 dark:text-gray-400 ml-auto">
              {filteredTerms.length} {filteredTerms.length === 1 ? 'term' : 'terms'}
            </span>
          </div>
        </div>
      </div>



      {/* Terms List */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {filteredTerms.length > 0 ? (
          <div className="space-y-4">
            {filteredTerms.map((term) => (
              <div
                key={term.id}
                className="bg-white dark:bg-gray-800 border border-slate-200 dark:border-gray-700 rounded-xl p-6 hover:border-purple-300 dark:hover:border-purple-600 hover:shadow-lg transition-all duration-300"
              >
                {/* Term Header */}
                <div className="flex items-start justify-between gap-4 mb-3">
                  <div className="flex-1">
                    <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-2">
                      {term.term}
                    </h3>
                    <p className="text-slate-600 dark:text-gray-400 leading-relaxed max-w-3xl">
                      {term.definition}
                    </p>
                  </div>



                  {/* Status Badge */}
                  <div className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-sm font-medium ${getStatusStyle(term.status)}`}>
                    {getStatusIcon(term.status)}
                    {term.status}
                  </div>
                </div>



                {/* Term Metadata */}
                <div className="flex flex-wrap items-center gap-4 pt-3 border-t border-slate-100 dark:border-gray-700">
                  {/* Domain */}
                  <div className="flex items-center gap-2 text-sm">
                    <Tag className="w-4 h-4 text-purple-600 dark:text-purple-400" />
                    <span className="text-slate-700 dark:text-gray-300 font-medium">
                      {term.domain}
                    </span>
                  </div>



                  {/* Owner */}
                  <div className="flex items-center gap-2 text-sm">
                    <User className="w-4 h-4 text-slate-500 dark:text-gray-400" />
                    <span className="text-slate-600 dark:text-gray-400">
                      {term.owner}
                    </span>
                  </div>



                  {/* Last Updated */}
                  <div className="flex items-center gap-2 text-sm ml-auto">
                    <Clock className="w-4 h-4 text-slate-400 dark:text-gray-500" />
                    <span className="text-slate-500 dark:text-gray-500">
                      Updated {new Date(term.lastUpdated).toLocaleDateString('en-US', { 
                        month: 'short', 
                        day: 'numeric', 
                        year: 'numeric' 
                      })}
                    </span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        ) : (
          // Empty State
          <div className="bg-white dark:bg-gray-800 border border-slate-200 dark:border-gray-700 rounded-xl p-12 text-center">
            <BookOpen className="w-16 h-16 text-slate-300 dark:text-gray-600 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-slate-900 dark:text-white mb-2">
              No terms found
            </h3>
            <p className="text-slate-600 dark:text-gray-400">
              {searchQuery || selectedDomain !== 'All' || selectedStatus !== 'All'
                ? 'Try adjusting your search or filters'
                : 'Get started by adding your first business term'}
            </p>
          </div>
        )}
      </div>
    </div>
  );
};



export default GlossaryPage;
